### ISSUE TITLE
User Story:  "color changing"

### ISSUE THREAD

**Issue by studtler** [Pyramid-S-C-H-E-M-E-for-short/store#5]
--User Story-- 
@Atessc & snake1

Title: Object Changes Color Based on Color Picker Selection

As a user,
I want to see a colorful object when I choose a color from the color picker,
So that the object visually reflects the color I’ve selected.

Technology: Continue with react

##Acceptance Criteria:
- When the user selects a color from the color picker, the object should immediately change to the selected color.
- If the user selects the color red, the object should change to the color red.
- The object should update dynamically and reflect any color chosen (e.g., blue, green, yellow, etc.).
- The color change should be smooth and visible without page reloads or delays.
- The color picker must support a variety of colors, and the object must reflect the exact color chosen.
- The color picker must be easy to interact with, and the object should be of a consistent size and shape (e.g., a square or circle) while the color changes.
- 
##Definition of Done:
- The object changes color immediately upon selection from the color picker.
- No bugs or errors when changing colors.
- Works on all supported browsers and devices.
- Code has been reviewed and tested.

Ideally a ticket should be done within a week but 2 weeks is fine for now..

**Comment by Atlessc** [comment]
PR for issue has been deployed
